### ISSUE TITLE
Copyright and license 版权与许可证

### ISSUE THREAD

**Issue by NKID00** [Lyt99/MuseDashModManager#3]
Do I have the rights to modify and redistribute this repository? Is this repository under any license?

我有权利修改和再分发这个项目吗？这个项目有许可证吗？

**Comment by Lyt99** [comment]
可以的，你可以在不侵犯官方利益(进行曲包破解等)的情况下使用这个项目，以及在官方做出表态时尽可能删除相关代码
目前没有加入许可证的打算，并且我们正在开发新的版本，近两天可能就会发布，该项目可能最近也会归档
