### ISSUE TITLE
补全缺失

### ISSUE THREAD

**Issue by lliuyuan** [Lyt99/MuseDashModManager#4]
那个补全缺失补哪个managed文件夹，以及补哪些

**Comment by Lyt99** [comment]
补齐在游戏目录底下MuseDash_Data\Managed文件夹下的引用
除了Assembly-CSharp.dll之外，应该还有一些杂七杂八的dll
不过该项目目前不维护了，游玩自定义曲目可以到 http://mdmc.moe/ 来获得相关信息
